### ISSUE TITLE
Error: watch elm-stuff ENOSPC + solution

### ISSUE THREAD

**Issue by ghost** [sporto/elm-navigation-pushstate#2]
Hello,

First, thank you for this great tutorial.

So...
When I tested your example, I had this error in my terminal (after the yarn start) :

```
yarn run v1.1.0
$ elm-live src/Main.elm --pushstate
Success! Compiled 1 module.                                         
Successfully generated index.html

elm-live:
  The build has succeeded. Starting the server!

[0000] info  Server running at http://localhost:8000/ (connect)
[0000] info  LiveReload running on 35729
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: watch elm-stuff ENOSPC
    at _errnoException (util.js:1026:11)
    at FSWatcher.start (fs.js:1383:19)
    at Object.fs.watch (fs.js:1409:11)
    at createFsWatchInstance (/elm-navigation-pushstate/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/elm-navigation-pushstate/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/elm-navigation-pushstate/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleDir (/elm-navigation-pushstate/node_modules/chokidar/lib/nodefs-handler.js:407:19)
    at FSWatcher.<anonymous> (/elm-navigation-pushstate/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at FSWatcher.<anonymous> (/elm-navigation-pushstate/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:154:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

After some researches, I found something [here](https://github.com/facebook/jest/issues/3254).
This following command solve the problem 👍 :
```echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p```

I don't know if it's the better solution but it works.

If someone have the same problem, maybe this will help him.
If you think that is relevant, maybe you can add it at the end of your README file.

PS: Sorry for my english, it's not my mother tongue.

Regards

Guillaume DUVAL

**Comment by flepied** [comment]
I have the same issue and I solved it by commenting the ulimit call in node_modules/react-native/local-cli/setup_env.sh
